Repository ITU-BDSA23-GROUP20/Chirp, pull requests merged in 2023-11, with the labels that each got.

#104 Fixed AuthorRepo.GetCheepsByAuthor methods guard clause
  src/Chirp.Infrastructure/Repository/AuthorRepository.cs
  src/Chirp.Web/Chirp.Web.csproj
  test/Chirp.InfrastructureTests/Chirp.InfrastructureTests.csproj
  test/Chirp.InfrastructureTests/ChirpDBContextUnitTests.cs
Labels: bug

#106 Creation of Partial View to replace duplicated code in the razor pages
  src/Chirp.Infrastructure/data/ChirpDBContext.db-shm
  src/Chirp.Infrastructure/data/ChirpDBContext.db-wal
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Shared/_CheepList.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml
Labels: enhancement

#120 Fixed Email being set as username
  src/Chirp.Infrastructure/Migrations/20231116133005_InitialCreate.Designer.cs
  src/Chirp.Infrastructure/Migrations/20231116133005_InitialCreate.cs
  src/Chirp.Infrastructure/data/ChirpDBContext.db
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Login.cshtml.cs
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml
  src/Chirp.Web/Areas/Identity/Pages/Account/Register.cshtml.cs
Labels: bug, Mads er Gud

#125 Sort Cheeps by Time rather than Id
  src/Chirp.Infrastructure/Repository/CheepRepository.cs
Labels: refactoring
